<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Click_CheckBox_AfterFiltering_Ops_Transactions_Templates_ClientEntity_BillPayTemplates</name>
   <tag></tag>
   <elementGuidId>18b9a613-6d78-4126-9c55-8c064aa58a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[contains(@class,'k-menu-group')]/li/div/form/ul[contains(@class,'k-multicheck-wrap')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1575553409601</value>
   </webElementProperties>
</WebElementEntity>
