<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillPay_Template_TemplateName_Input</name>
   <tag></tag>
   <elementGuidId>4fb81290-03f4-47ce-a9de-af95ee94d3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//body[@ng-controller='BodyController']//div[@class='k-animation-container'])[3]/div/ul/li[6]/div/ul/li/div/form/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>(//body[@ng-controller='BodyController']//div[@class='k-animation-container'])[3]/div/ul/li[6]/div/ul/li/div/form/div[1]/input</value>
   </webElementXpaths>
</WebElementEntity>
