<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundInvestorIncomePct</name>
   <tag></tag>
   <elementGuidId>32dd43f5-74fc-4606-96f1-467118621e6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;efiApprovalForm&quot;]/div/div[11]/div/common-data-entry/div/div/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
