<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundInvestorPerfFeeOverride</name>
   <tag></tag>
   <elementGuidId>72a84e75-ba94-4f65-bead-a1e15d00bf08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;efiApprovalForm&quot;]/div/div[16]/div/common-data-entry/div/div/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
