<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FundInvestorMgmtFeeOverride</name>
   <tag></tag>
   <elementGuidId>e8ac31b5-b4e8-4e0c-96f5-6583be9c592c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;efiApprovalForm&quot;]/div/div[15]/div/common-data-entry/div/div/span/span/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
