<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EntityClosingGroup</name>
   <tag></tag>
   <elementGuidId>699a4e77-7b61-40f5-99c9-293ea483d27c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='row']//div[2]//common-data-entry[1]//div[1]//div[1]//span[1]//span[1]//input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
