<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clicking_On_Close_After_Account_Creation</name>
   <tag></tag>
   <elementGuidId>c414b60b-cfb2-416f-9e51-4d212926090d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;crmAccountViewer&quot;]/crm-account-viewer/div//button[contains(@ng-click,'localClose')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
