<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BillPay_Summary_TemplateType</name>
   <tag></tag>
   <elementGuidId>fd52ec93-230b-43e6-a213-eebe96dc090f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='leftpane']/widget[1]/div/div/div[2]/div/div[2]/div/form/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;leftpane&quot;]/widget[1]/div/div/div[2]/div/div[2]/div[1]/form/div[1]/select</value>
   </webElementXpaths>
</WebElementEntity>
