<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Clicking_Back_Button_After_AccountCreation</name>
   <tag></tag>
   <elementGuidId>ef87ee7f-93c9-4a41-8af6-8bd8a5b13100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ewiInfoPane']/workflow-panel/div/ul/li/a[contains(text(),'History']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-arrow-circle-left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crmAccountViewer&quot;)/crm-account-viewer[1]/div[@class=&quot;clearfix header well crmviewer-header&quot;]/div[@class=&quot;col-md-6 pull-center&quot;]/h2[1]/a[1]/i[@class=&quot;fa fa-arrow-circle-left&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='crmAccountViewer']/crm-account-viewer/div/div[2]/h2/a/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//crm-account-viewer/div/div[2]/h2/a/i</value>
   </webElementXpaths>
</WebElementEntity>
