<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>validating_RelationName_Operations_ManualPrice</name>
   <tag></tag>
   <elementGuidId>c4d28b91-c059-4475-9151-daad5542f0b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='manualPricingTaskList']/div/table/tbody/tr/td/span[contains(@ng-bind,'relationship')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
