<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GLExpenseAccount_Input</name>
   <tag></tag>
   <elementGuidId>5ad2b185-6b43-4601-8ce6-4df5317ae802</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id='ddlGlDebit23-list']/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <value>//*[@id=&quot;ddlGlCredit-list&quot;]/span/input</value>
   </webElementXpaths>
</WebElementEntity>
